name: bash-static Image CI

on:
  push:
    branches:
    - 'master'
    paths:
    - '.github/workflows/bash-static.yml'
    - 'bash-static/Dockerfile'
  schedule:
  - cron: "10 2 1-31/10 * *"
  workflow_dispatch:

env:
  bash-static_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/bash-static

jobs:
  bash-static:
    runs-on: ${{ matrix.platform == 'linux/arm64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:bash-static"
          push: true
          platforms: ${{ matrix.platform }}
          cache-from: type=gha,scope=${{ matrix.platform }}
          cache-to: type=gha,mode=max,scope=${{ matrix.platform }}
          outputs: type=image,compression=estargz,force-compression=true,oci-mediatypes=true,name=${{ env.bash-static_IMAGE }},push-by-digest=true,name-canonical=true,push=true
      -
        name: Export digest
        run: |
          mkdir -p /tmp/bash-static-digests/
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/bash-static-digests/${digest#sha256:}"          

          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV
      -
        name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: bash-static-digests-${{ env.PLATFORM_PAIR }}
          path: /tmp/bash-static-digests/*
          if-no-files-found: error
          retention-days: 1

  bash-static-multiarch:
    runs-on: ubuntu-24.04
    needs:
      - bash-static
    steps:
      -
        name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/bash-static-digests/
          pattern: bash-static-digests-*
          merge-multiple: true
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Create manifest list and push
        working-directory: /tmp/bash-static-digests/
        run: |
          docker buildx imagetools create --tag ${{ env.bash-static_IMAGE }}:latest \
              $(printf '${{ env.bash-static_IMAGE }}@sha256:%s ' *)          
      -
        name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.bash-static_IMAGE }}:latest \
              | grep -Po '[^ \r\n\t\v]+@sha256:[a-z0-9]+' | xargs -r -t -n 1 docker buildx imagetools inspect --raw
      -
        name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: "${{ env.bash-static_IMAGE }}:latest"
          format: 'table'
