name: Caddy Image CI

on:
  push:
    branches:
    - 'master'
    paths:
    - '.github/workflows/caddy.yml'
    - 'caddy/**'
  schedule:
  - cron: "50 1 * * *"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:caddy"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/caddy:cfdns
