name: saveweb Images CI

on:
  push:
    branches:
    - 'master'
    paths:
    - '.github/workflows/saveweb.yml'
    - 'saveweb/**'
  schedule:
  - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: "./Dockerfile.huashijie"
            tag: saveweb:huashijie
          - dockerfile: "./Dockerfile.lowapk_v2"
            tag: saveweb:lowapk-v2
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:saveweb"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.tag }}
          file: ${{ matrix.dockerfile }}
