name: saveweb Images CI

on:
  push:
    branches:
    - 'master'
    paths:
    - '.github/workflows/saveweb.yml'
    - 'saveweb/**'
  schedule:
  - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: lowapk_v2
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:saveweb"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/saveweb:lowapk-v2
          file: "./Dockerfile.lowapk_v2"
      -
        name: huashijie
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:saveweb"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/saveweb:huashijie
          file: "./Dockerfile.huashijie"
