name: saveweb Images CI

on:
  push:
    branches:
    - 'master'
    paths:
    - '.github/workflows/saveweb.yml'
    - 'saveweb/**'
  schedule:
  - cron: "30 1 * * *"
  workflow_dispatch:

jobs:
  huashijie:
    name: huashijie
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
           - tag: saveweb:huashijie-amd
             dockerfile: "./Dockerfile.huashijie"
             platforms: linux/amd64
           - tag: saveweb:huashijie-arm
             dockerfile: "./Dockerfile.huashijie"
             platforms: linux/arm64
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:saveweb"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.tag }}
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platforms }}

  huashijie-multiarch:
    runs-on: ubuntu-latest
    needs:
      - huashijie
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Create multiarch image
        run: |
          docker manifest create ${{ secrets.DOCKERHUB_USERNAME }}/saveweb:huashijie \
              --amend ${{ secrets.DOCKERHUB_USERNAME }}/saveweb:huashijie-amd \
              --amend ${{ secrets.DOCKERHUB_USERNAME }}/saveweb:huashijie-arm
          docker manifest push ${{ secrets.DOCKERHUB_USERNAME }}/saveweb:huashijie

  lowapk-v2:
    name: lowapk-v2
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
           - tag: saveweb:lowapk-v2-amd
             dockerfile: "./Dockerfile.lowapk_v2"
             platforms: linux/amd64
           - tag: saveweb:lowapk-v2-arm
             dockerfile: "./Dockerfile.lowapk_v2"
             platforms: linux/arm64
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:saveweb"
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.tag }}
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platforms }}

  lowapk-v2-multiarch:
    runs-on: ubuntu-latest
    needs:
      - lowapk-v2
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Create multiarch image
        run: |
          docker manifest create ${{ secrets.DOCKERHUB_USERNAME }}/saveweb:lowapk-v2 \
              --amend ${{ secrets.DOCKERHUB_USERNAME }}/saveweb:lowapk-v2-amd \
              --amend ${{ secrets.DOCKERHUB_USERNAME }}/saveweb:lowapk-v2-arm
          docker manifest push ${{ secrets.DOCKERHUB_USERNAME }}/saveweb:lowapk-v2
